name: Build for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for Raspberry Pi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Dependencies
        run: |
          go mod tidy

      - name: Build Binary for Raspberry Pi
        run: |
          # Set environment variables for Raspberry Pi ARM architecture
          GOOS=linux GOARCH=arm GOARM=7 go build -o alsamixer2mqtt .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: alsamixer2mqtt
          path: alsamixer2mqtt
